### ISSUE TITLE
.

### ISSUE THREAD

**Issue by graysuit** [kirilamenski/RDroid#2]

**Comment by kirilamenski** [comment]
Hey @graysuit !
Neither one thing nor the other. with this program you will not be able to remotely connect to any phone. It's more visual interface for ADB commands. Which allows you to manage your android phone via a USB cable.

**Comment by graysuit** [comment]
Oh ! Its mean its GUI of adb. Right ?

**Comment by kirilamenski** [comment]
Yes, it is right.

**Comment by graysuit** [comment]
Thanks.
